# Generated by Django 5.2.6 on 2025-09-24 12:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_choosetopics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choosetopics",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="topic_image",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "heic", "jfif"]
                    )
                ],
            ),
        ),
    ]
