# Generated by Django 5.2.6 on 2025-09-24 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_choosetopics_profile_pic"),
    ]

    operations = [
        migrations.RenameField(
            model_name="choosetopics",
            old_name="available",
            new_name="is_available",
        ),
    ]
