# Generated by Django 5.2.6 on 2025-09-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_chooselevel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chooselevel",
            name="level",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
