# Generated by Django 5.2.6 on 2025-09-25 07:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_userselectedtopics"),
    ]

    operations = [
        migrations.AddField(
            model_name="usergoal",
            name="select_topics",
            field=models.ForeignKey(
                default=datetime.datetime(
                    2025, 9, 25, 7, 47, 26, 644777, tzinfo=datetime.timezone.utc
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="users.userselectedtopics",
            ),
            preserve_default=False,
        ),
    ]
