# Generated by Django 5.2.6 on 2025-09-25 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_usergoal_select_topics"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usergoal",
            name="select_topics",
        ),
    ]
