# Generated by Django 5.2.6 on 2025-09-25 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_remove_usergoal_select_topics"),
    ]

    operations = [
        migrations.AddField(
            model_name="usergoal",
            name="select_topic_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_select_topic",
                to="users.userselectedtopics",
            ),
            preserve_default=False,
        ),
    ]
