# Generated by Django 5.2.6 on 2025-09-25 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_usergoal_select_topic_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usergoal",
            old_name="select_topic_id",
            new_name="select_topic",
        ),
    ]
