# Generated by Django 5.2.6 on 2025-09-29 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_rename_select_topic_id_usergoal_select_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="time",
            field=models.TimeField(
                default=datetime.datetime(
                    2025, 9, 29, 5, 58, 4, 233988, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="goal",
            name="week",
            field=models.CharField(
                choices=[
                    ("sun", "sun"),
                    ("mon", "mon"),
                    ("tue", "tue"),
                    ("wed", "wed"),
                    ("thu", "thu"),
                    ("fri", "fri"),
                    ("sat", "sat"),
                ],
                default=datetime.datetime(
                    2025, 9, 29, 5, 58, 11, 809681, tzinfo=datetime.timezone.utc
                ),
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
