# Generated by Django 5.2.6 on 2025-09-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_event_created_at_event_deleted_at_event_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
