# Generated by Django 5.2.6 on 2025-09-29 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_alter_goal_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="description",
            field=models.TextField(
                default=datetime.datetime(
                    2025, 9, 29, 7, 20, 21, 151781, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
