# Generated by Django 5.2.6 on 2025-09-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_goal_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pofile_image",
            field=models.ImageField(blank=True, null=True, upload_to="user-profile/"),
        ),
    ]
