# Generated by Django 5.2.6 on 2025-09-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_home"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="home",
            name="goal",
        ),
        migrations.AddField(
            model_name="home",
            name="goal",
            field=models.ManyToManyField(to="users.goal"),
        ),
    ]
