# Generated by Django 5.2.6 on 2025-09-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_remove_home_goal_home_goal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="home",
            name="title",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
