# Generated by Django 5.2.6 on 2025-10-06 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_translate_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="translate",
            name="users",
        ),
    ]
