# Generated by Django 5.2.6 on 2025-10-06 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_remove_translate_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="goal_images",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "heic", "jfif"]
                    )
                ],
            ),
        ),
    ]
