# Generated by Django 5.2.6 on 2025-10-07 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_goal_name_goal_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goal",
            name="name",
        ),
        migrations.RemoveField(
            model_name="goal",
            name="profile_image",
        ),
    ]
