# Generated by Django 5.2.6 on 2025-10-08 05:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_remove_goal_name_remove_goal_profile_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAim",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=120)),
                ("description", models.CharField(max_length=250)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="English",
        ),
    ]
