# Generated by Django 5.2.6 on 2025-10-08 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0027_useraim_delete_english"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usergoal",
            name="goal",
        ),
        migrations.RemoveField(
            model_name="usergoal",
            name="select_topic",
        ),
        migrations.RemoveField(
            model_name="usergoal",
            name="user",
        ),
        migrations.AddField(
            model_name="usergoal",
            name="title",
            field=models.CharField(
                default=datetime.datetime(
                    2025, 10, 8, 6, 39, 52, 894221, tzinfo=datetime.timezone.utc
                ),
                max_length=120,
            ),
            preserve_default=False,
        ),
    ]
