# Generated by Django 5.2.6 on 2025-10-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_remove_usergoal_goal_remove_usergoal_select_topic_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goal",
            name="description",
        ),
        migrations.RemoveField(
            model_name="goal",
            name="title",
        ),
        migrations.AlterField(
            model_name="goal",
            name="week",
            field=models.CharField(
                choices=[
                    ("Sun", "Sun"),
                    ("Mon", "Mon"),
                    ("Tue", "Tue"),
                    ("Wed", "Wed"),
                    ("Thu", "Thu"),
                    ("Fri", "Fri"),
                    ("Sat", "Sat"),
                ],
                max_length=50,
            ),
        ),
        migrations.DeleteModel(
            name="UserSelectedTopics",
        ),
    ]
