# Generated by Django 5.2.6 on 2025-10-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0029_remove_goal_description_remove_goal_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="time",
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
