# Generated by Django 5.2.6 on 2025-10-08 07:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0031_selectlevel_delete_chooselevel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="home",
            name="description",
        ),
        migrations.RemoveField(
            model_name="home",
            name="plan",
        ),
        migrations.AddField(
            model_name="home",
            name="time",
            field=models.CharField(
                default=datetime.datetime(
                    2025, 10, 8, 7, 52, 18, 969266, tzinfo=datetime.timezone.utc
                ),
                max_length=120,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="home",
            name="translate",
            field=models.ForeignKey(
                default=datetime.datetime(
                    2025, 10, 8, 7, 52, 28, 945486, tzinfo=datetime.timezone.utc
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="users.translate",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="home",
            name="user_goal",
            field=models.ForeignKey(
                default=datetime.datetime(
                    2025, 10, 8, 7, 52, 36, 881290, tzinfo=datetime.timezone.utc
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="users.usergoal",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="home",
            name="title",
            field=models.CharField(
                default=datetime.datetime(
                    2025, 10, 8, 7, 52, 40, 89168, tzinfo=datetime.timezone.utc
                ),
                max_length=250,
            ),
            preserve_default=False,
        ),
    ]
