# Generated by Django 5.2.6 on 2025-10-08 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0032_remove_home_description_remove_home_plan_home_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home",
            name="translate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.translate",
            ),
        ),
    ]
