# Generated by Django 5.2.6 on 2025-10-08 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0033_alter_home_translate"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="goal",
            field=models.ForeignKey(
                auto_created="goals",
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.goal",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_aim",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users_aim",
                to="users.useraim",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_goal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users_goal",
                to="users.usergoal",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_topics",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users_topics",
                to="users.choosetopics",
            ),
        ),
    ]
