# Generated by Django 5.2.6 on 2025-10-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0034_user_goal_user_user_aim_user_user_goal_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_topics",
        ),
        migrations.AddField(
            model_name="user",
            name="user_topics",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="users_topics",
                to="users.choosetopics",
            ),
        ),
    ]
