# Generated by Django 5.2.6 on 2025-10-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0035_remove_user_user_topics_user_user_topics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_topics",
            field=models.ManyToManyField(
                related_name="users_topics", to="users.choosetopics"
            ),
        ),
    ]
