# Generated by Django 5.2.6 on 2025-10-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0036_alter_user_user_topics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_topics",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="users_topics",
                to="users.choosetopics",
            ),
        ),
    ]
