# Generated by Django 5.2.6 on 2025-10-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0037_alter_user_user_topics"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="onboarding_steps",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "STEP 1"),
                    ("2", "STEP 2"),
                    ("3", "STEP 3"),
                    ("4", "STEP 4"),
                    ("5", "STEP 5"),
                    ("6", "STEP 6"),
                    ("7", "STEP 7"),
                    ("8", "STEP 8"),
                    ("9", "STEP 9"),
                    ("10", "STEP 10"),
                    ("11", "STEP 11"),
                    ("12", "COMPLETED"),
                ],
                max_length=3,
                null=True,
            ),
        ),
    ]
