# Generated by Django 5.2.6 on 2025-10-09 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0038_user_onboarding_steps"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 10, 9, 6, 50, 24, 638344, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="day",
            field=models.CharField(
                default=datetime.datetime(
                    2025, 10, 9, 6, 50, 28, 837877, tzinfo=datetime.timezone.utc
                ),
                max_length=120,
            ),
            preserve_default=False,
        ),
    ]
