# Generated by Django 5.2.6 on 2025-10-09 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0039_event_date_event_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="month",
            field=models.CharField(
                choices=[
                    ("January", "January"),
                    ("February", "February"),
                    ("March", "March"),
                    ("April", "April"),
                    ("May", "May"),
                    ("June", "June"),
                    ("July", "July"),
                    ("August", "August"),
                    ("September", "September"),
                    ("October", "October"),
                    ("November", "November"),
                    ("December", "December"),
                ],
                default=datetime.datetime(2025, 10, 9, 13, 9, 26, 65081),
                max_length=120,
            ),
            preserve_default=False,
        ),
    ]
