# Generated by Django 5.2.6 on 2025-10-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0041_alter_event_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="goal",
        ),
        migrations.AddField(
            model_name="user",
            name="goal",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="goals", to="users.goal"
            ),
        ),
    ]
