# Generated by Django 5.2.6 on 2025-10-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0043_remove_user_goal_goalrelation"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="goal",
            field=models.ManyToManyField(
                blank=True,
                related_name="goals",
                through="users.GoalRelation",
                to="users.goal",
            ),
        ),
    ]
