# Generated by Django 5.2.6 on 2025-10-09 18:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0044_user_goal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_topics",
        ),
        migrations.CreateModel(
            name="UserTopicsRelation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "topics",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.choosetopics",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
