# Generated by Django 5.2.6 on 2025-10-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0045_remove_user_user_topics_usertopicsrelation"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_topics",
            field=models.ManyToManyField(
                blank=True,
                related_name="users_topics",
                through="users.UserTopicsRelation",
                to="users.choosetopics",
            ),
        ),
    ]
