# Generated by Django 5.2.6 on 2025-10-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0046_user_user_topics"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_goal",
        ),
        migrations.AddField(
            model_name="user",
            name="user_goal",
            field=models.ManyToManyField(
                blank=True, related_name="users_goal", to="users.usergoal"
            ),
        ),
    ]
