# Generated by Django 5.2.6 on 2025-10-10 10:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0047_remove_user_user_goal_user_user_goal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_goal",
        ),
        migrations.CreateModel(
            name="UserGoalRelation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.usergoal"
                    ),
                ),
            ],
        ),
    ]
