# Generated by Django 5.2.6 on 2025-10-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0048_remove_user_user_goal_usergoalrelation"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_goal",
            field=models.ManyToManyField(
                blank=True,
                related_name="users_goal",
                through="users.UserGoalRelation",
                to="users.usergoal",
            ),
        ),
    ]
