# Generated by Django 5.2.6 on 2025-10-10 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0049_user_user_goal"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="title",
            field=models.CharField(
                default=datetime.datetime(2025, 10, 10, 11, 32, 7, 962324),
                max_length=120,
            ),
            preserve_default=False,
        ),
    ]
