# Generated by Django 5.2.6 on 2025-10-10 12:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0050_goal_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="home",
            name="translate",
        ),
        migrations.AddField(
            model_name="home",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2025, 10, 10, 12, 21, 58, 960497)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="home",
            name="plan",
            field=models.CharField(
                default=datetime.datetime(2025, 10, 10, 12, 22, 8, 649192),
                max_length=120,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="goal",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="home",
            name="goal",
        ),
        migrations.AlterField(
            model_name="home",
            name="time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="home",
            name="title",
            field=models.CharField(max_length=120),
        ),
        migrations.AddField(
            model_name="home",
            name="goal",
            field=models.ForeignKey(
                default=datetime.datetime(2025, 10, 10, 12, 22, 18, 809109),
                on_delete=django.db.models.deletion.CASCADE,
                to="users.goal",
            ),
            preserve_default=False,
        ),
    ]
