# Generated by Django 5.2.6 on 2025-10-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0051_remove_home_translate_home_date_home_plan_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="home",
            name="user_goal",
        ),
        migrations.AddField(
            model_name="home",
            name="user_goal",
            field=models.ManyToManyField(
                blank=True, related_name="user_goal", to="users.usergoal"
            ),
        ),
    ]
