# Generated by Django 5.2.6 on 2025-10-10 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0052_remove_home_user_goal_home_user_goal"),
    ]

    operations = [
        migrations.RenameField(
            model_name="choosetopics",
            old_name="profile_pic",
            new_name="topic_image",
        ),
        migrations.RemoveField(
            model_name="choosetopics",
            name="is_available",
        ),
    ]
