# Generated by Django 5.2.6 on 2025-10-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0053_rename_profile_pic_choosetopics_topic_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="choosetopics",
            old_name="topic_image",
            new_name="logo",
        ),
        migrations.AlterField(
            model_name="useraim",
            name="title",
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name="usergoal",
            name="title",
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
