# Generated by Django 5.2.6 on 2025-10-10 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0054_rename_topic_image_choosetopics_logo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_aim",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users_aim",
                to="users.useraim",
            ),
        ),
    ]
