# Generated by Django 5.2.6 on 2025-10-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0055_alter_user_user_aim"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usergoal",
            name="value",
            field=models.IntegerField(editable=False),
        ),
    ]
