# Generated by Django 5.2.6 on 2025-10-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0056_alter_usergoal_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usergoal",
            name="value",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
