# Generated by Django 5.2.6 on 2025-10-10 16:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0057_alter_usergoal_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goal",
            name="time",
        ),
        migrations.AlterField(
            model_name="goal",
            name="week",
            field=models.CharField(
                choices=[
                    ("Sun", "Sun"),
                    ("Mon", "Mon"),
                    ("Tue", "Tue"),
                    ("Wed", "Wed"),
                    ("Thu", "Thu"),
                    ("Fri", "Fri"),
                    ("Sat", "Sat"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="GoalSchedule",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("per_day", models.CharField(blank=True, max_length=120, null=True)),
                ("days", models.ManyToManyField(blank=True, to="users.goal")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goal_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
