# Generated by Django 5.2.6 on 2025-10-10 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0058_remove_goal_time_alter_goal_week_goalschedule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goal",
            name="title",
        ),
    ]
