# Generated by Django 5.2.6 on 2025-10-10 19:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0059_remove_goal_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goalschedule",
            name="days",
        ),
        migrations.CreateModel(
            name="GoalScheduleRelation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.goal"
                    ),
                ),
                (
                    "goal_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.goalschedule",
                    ),
                ),
            ],
        ),
    ]
