# Generated by Django 5.2.6 on 2025-10-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0060_remove_goalschedule_days_goalschedulerelation"),
    ]

    operations = [
        migrations.AddField(
            model_name="goalschedule",
            name="days",
            field=models.ManyToManyField(
                blank=True, through="users.GoalScheduleRelation", to="users.goal"
            ),
        ),
    ]
