# Generated by Django 5.2.6 on 2025-10-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0061_goalschedule_days"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goalschedulerelation",
            name="goal_schedule",
        ),
        migrations.AddField(
            model_name="user",
            name="per_day",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.DeleteModel(
            name="GoalSchedule",
        ),
    ]
