# Generated by Django 5.2.6 on 2025-10-10 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0062_remove_goalschedulerelation_goal_schedule_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GoalScheduleRelation",
        ),
    ]
