# Generated by Django 5.2.6 on 2025-10-15 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0065_friendship"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="friendship",
            unique_together={("from_user", "to_user")},
        ),
    ]
