# Generated by Django 5.2.6 on 2025-10-15 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0005_alter_notification_unique_together"),
        ("users", "0066_alter_friendship_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendship",
            name="notification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="notification.notification",
            ),
        ),
    ]
