# Generated by Django 5.2.6 on 2025-09-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
