# Generated by Django 5.2.6 on 2025-10-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0002_plan_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="plan_image",
            field=models.FileField(blank=True, null=True, upload_to="plan_images/"),
        ),
    ]
