# Generated by Django 5.2.6 on 2025-10-15 13:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0004_notification_is_read_notification_message_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="notification",
            unique_together={("sender", "receiver")},
        ),
    ]
