# Generated by Django 5.2.6 on 2025-10-07 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exercise", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vocabularyexercise",
            name="grammar_exercise",
        ),
    ]
