# Generated by Django 5.2.6 on 2025-10-07 10:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercise", "0003_studymaterials"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studymaterials",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="study_materials/songs/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "mp3",
                            ".mp3",
                            ".aac",
                            ".wav",
                            ".aiff",
                            ".flac",
                            ".alac",
                        ]
                    )
                ],
            ),
        ),
    ]
