# Generated by Django 5.2.6 on 2025-10-07 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exercise", "0004_alter_studymaterials_file"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StudyMaterials",
        ),
    ]
