# Generated by Django 5.2.6 on 2025-10-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercise", "0006_article_books_interview_song"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="tag",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="books",
            name="tag",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="interview",
            name="tag",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="song",
            name="tag",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
