# Generated by Django 5.2.6 on 2025-10-07 12:45

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercise", "0007_alter_article_tag_alter_books_tag_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(
                default=datetime.datetime(
                    2025, 10, 7, 12, 45, 22, 693604, tzinfo=datetime.timezone.utc
                ),
                upload_to="study_materials/article",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "heic", "jfif"]
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="books",
            name="image",
            field=models.ImageField(
                default=datetime.datetime(
                    2025, 10, 7, 12, 45, 29, 478258, tzinfo=datetime.timezone.utc
                ),
                upload_to="study_materials/books",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "heic", "jfif"]
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="interview",
            name="image",
            field=models.ImageField(
                default=datetime.datetime(
                    2025, 10, 7, 12, 45, 32, 165071, tzinfo=datetime.timezone.utc
                ),
                upload_to="study_materials/interview",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "heic", "jfif"]
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="song",
            name="file",
            field=models.FileField(
                default=datetime.datetime(
                    2025, 10, 7, 12, 45, 35, 781498, tzinfo=datetime.timezone.utc
                ),
                upload_to="study_materials/songs/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "mp3",
                            ".mp3",
                            ".aac",
                            ".wav",
                            ".aiff",
                            ".flac",
                            ".alac",
                        ]
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="song",
            name="image",
            field=models.ImageField(
                default=datetime.datetime(
                    2025, 10, 7, 12, 45, 51, 149233, tzinfo=datetime.timezone.utc
                ),
                upload_to="study_materials/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "heic", "jfif"]
                    )
                ],
            ),
            preserve_default=False,
        ),
    ]
