# Generated by Django 5.2.6 on 2025-10-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercise", "0008_alter_article_image_alter_books_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grammarexercise",
            name="range",
        ),
        migrations.RemoveField(
            model_name="vocabularyexercise",
            name="range",
        ),
        migrations.AddField(
            model_name="grammarexercise",
            name="level",
            field=models.CharField(default="Elementary", max_length=255),
        ),
        migrations.AddField(
            model_name="vocabularyexercise",
            name="level",
            field=models.CharField(default="Elementary", max_length=255),
        ),
    ]
