# Generated by Django 5.2.6 on 2025-10-07 14:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercise", "0009_remove_grammarexercise_range_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("phrase", models.CharField(max_length=255)),
                ("question", models.CharField(max_length=250)),
                ("option_a", models.CharField(max_length=100)),
                ("option_b", models.CharField(max_length=100)),
                ("correct_option", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
